# jwt configuration
jwt:
  signing-key: pddZl
  expires-time: 7d
  buffer-time: 1d
  issuer: pddZl

# zap logger configuration
zap:
  level: info
  format: console
  prefix: '[TD27]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# 日志割接
rotateLogs:
  max-size: 10
  max-backups: 5
  max-age: 7
  compress: false

# system configuration
system:
  env: 'production' # Change to "develop" to skip authentication for development mode
  host: '0.0.0.0'
  port: '8888'
  stack: false

# mysql configuration
mysql:
  path: 'mysql'
  port: 3306
  config: 'charset=utf8&parseTime=true'
  db-name: 'td27'
  username: 'root'
  password: 'td27_2022'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: false

# redis configuration
redis:
  db: 0
  path: 'redis'
  port: 6379
  password: ''

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
